#SPDX-License-Identifier: MIT-0
---
# handlers file for grafana
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart grafana
  systemd:
    name: "{{ grafana_service_name }}.service"
    state: restarted
